added cosign

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -28,6 +28,9 @@ jobs:
       - name: Install Trivy
         uses: aquasecurity/setup-trivy@v0.2.1
 
+      - name: Install Cosign
+        uses: sigstore/cosign-installer@v3.4.0
+
       - name: Checkout source
         uses: actions/checkout@v3
 
@@ -46,12 +49,26 @@ jobs:
                           -u "$ACR_USERNAME" \
                           --password-stdin
 
+
+      - name: Write Cosign key to disk
+        run: |
+          echo "${{ secrets.COSIGN_PRIVATE_KEY }}" > cosign.key
+          chmod 600 cosign.key
+
+
       - name: Build Docker image
         run: |
           docker buildx build \
             -t "$ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG" \
             --push \
             .
+
+      - name: Sign the image with Cosign
+        env:
+          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
+        run: |
+          cosign sign --key cosign.key $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG
+
 
       - name: Generate SBOM (Syft)
         uses: anchore/sbom-action@v0.20.1
@@ -143,6 +160,18 @@ jobs:
             else
               echo "No files found in ./artifacts/ — skipping upload."
             fi
+
+      - name: Gate Deployment on Signature Check
+        run: |
+          cosign verify --key cosign.key $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG > verify.log
+          if grep -q "Verified OK" verify.log; then
+            echo "✅ Signature verified"
+          else
+            echo "❌ Signature verification failed! This Container imaged is not signed or the signature is invalid. Deployment aborted."
+            cat verify.log
+            exit 1
+          fi
+
 
       - name: Deploy to Azure Container Instance
         shell: bash
